### ISSUE TITLE
観光アンケートコメント新着分のグラフの色調整

### ISSUE THREAD

**Issue by NaobumiTanaka** [code4fukui/fukui-kanko-reservation#2]
![313077965_619048959971631_5885823780052236773_n](https://github.com/code4fukui/fukui-kanko-reservation/assets/107970041/2f0e3351-a919-4dd7-94f8-c6edeee58bf6)
https://code4fukui.github.io/fukui-kanko-stat/comment.html#0,0,0,0
このグラフの色調ですが、昨年度に統一させた
https://code4fukui.github.io/fukui-kanko-stat/
↑こちらの色調にあわせてもらえるとうれしいです。
添付が昨年度に策定したデザインルールですー

**Comment by binc-tanaka** [comment]
修正完了しました
